### PR TITLE
Updating dependencies

### PR DESCRIPTION
**Pull request by alakra**
I am using the latest `httpoison (~0.8)` and `poison (~2.1)` libraries in my app and needed these dependencies updated so I wouldn't have conflicts in my package resolutions.

Thanks for looking at this! :heart:

### CODE REVIEW

**Comment by slashdotdash** [comment]
I have similar dependency conflicts between this library and `poison`/`httpoison`. Currently solved by using the `override: true` flag for the poison dependency. 

This PR would alleviate the need for that workaround. Thanks

**Comment by alakra** [comment]
Bump.

**Comment by scrogson** [comment]
Sorry for the delay. I've decided to merge #49 as it was more permissive.

**Comment by alakra** [comment]
Works for me. Thanks!

**Pull request closed without merging**
