### PR TITLE
specify hackney requirements

### PR DESCRIPTION
**Pull request by stephenmoloney**
***Description:***

- relax hackney requirements

- I didn't increase to `1.10.1` and `1.11.0` deliberately as there are some issues with those versions of hackney in the hackney issues list. But I can include them if needed.

### CODE REVIEW

**Comment by scrogson** [comment]
❤️

**Comment by Tsuyoshi84** [comment]
Hi, I'm trying to use oauth2 and [bamboo](https://github.com/thoughtbot/bamboo) in the same project. However, since each library is specifying different version of hackney, I have to override the hackney version explicitly. I'm not sure what exactly "some issues" are referring to, so I wonder if it is safe to use the latest version of hackney, I mean 1.13. I'd be happy if I could hear any thoughts :D
Thank you.

**Comment by mjankowski** [comment]
I have same issue as above (Bamboo and Oauth2 in same project) and hit the same upgrade issue re: locked hackney version from oauth2 package.

I forked oauth2 and bumped the hackney dep to latest (1.14 now) and the oauth2 test suite passes ... curious to hear what the actual issue is with hackney here. Maybe it's been resolved in more recent releases since the original version range lock?

**Comment by stephenmoloney** [comment]
I was having issues in some old versions of hackney quite some time ago. 
There were a number of related issues - this being one of them `https://github.com/benoitc/hackney/issues/447` 

Given that those issues are now closed in hackney, I'm also in favor of removing this restriction.

**Pull request merged**
