### PR TITLE
Update dependencies to work with phoenix 0.9.0

### PR DESCRIPTION
**Pull request by atbyrd**

### CODE REVIEW

**Comment by atbyrd** [comment]
I've also added support for google by adding the scope parameter

**Comment by scrogson** [comment]
@atbyrd you should be able to pass the `scope` into the `params` map for the request.

Example:
```elixir
AuthCode.authorize_url(strategy, %{redirect_uri: "https://example.com/auth/callback", scope: "email"})
```

The `scope` param is not something I believe belongs in the strategy itself, but rather one level up in some code that would abstract the details of Google's specific requirements.

Feel free to revert those scope related commits and I'll look into merging the dependency updates.

Let me know if you need any more help.

**Comment by atbyrd** [comment]
I rolled back the scope changes, thanks

**Comment by scrogson** [comment]
Hey @atbyrd I've just merged #10 as it updates the plug dependency to a more recent version. Sorry I didn't get around to reviewing your PR sooner.

**Pull request closed without merging**
