### PR TITLE
update hackney dependency to 1.7

### PR DESCRIPTION
**Pull request by slashmili**
Possible fix for borken google OAuth2.

check #90 for more detail

### CODE REVIEW

**Comment by scrogson** [comment]
Hey @slashmili thanks. I've been looking into this since you created #90. I see there was an [issue](https://github.com/benoitc/hackney/issues/388) reported for `hackney` which prompted reverting `1.6.6` and releasing `1.7.0` and then `1.7.1`.

I was in the middle of bumping the dependency and getting ready for a new release and noticed the tests were failing because of the duplicate `authorization`, `accept`, and `content-type` headers.

I'm going to continue to look into this later today as I want to make sure that `oauth2` is not ultimately responsible for this. It seems odd that it was working fine with `1.6.5` and not now.

**Comment by scrogson** [comment]
Ok, so it looks to me that `oauth2` has potentially been sending duplicate headers through `hackney` this whole time but it wasn't until recently that it was noticed due to `hackney` deduping them until recently.

👍

**Comment by slashmili** [comment]
@scrogson Could you also publish the changes to hex?

**Comment by scrogson** [comment]
@slashmili I published 0.9.1 on Friday.

**Pull request merged**
