### PR TITLE
Spring cleaning

### PR DESCRIPTION
**Pull request by woylie**
Just a bit of (admittedly oddly timed) spring cleaning.

- add formatter config and format code
- dependency updates
- add, fix and improve type specs
- improve error handling in content-type extraction
- some typo fixes
- add credo
- update ci config

I'm a bit confused about the case statement in `OAuth2.Request.request/5`:

```elixir
case :hackney.request(method, url, headers, body, req_opts) do
  {:ok, ref} when is_reference(ref) ->
    {:ok, ref}

  {:ok, status, headers, ref} when is_reference(ref) ->
    process_body(client, status, headers, ref)

  {:ok, status, headers, body} when is_binary(body) ->
    process_body(client, status, headers, body)

  {:error, reason} ->
    {:error, %Error{reason: reason}}
end
```

According to the documentation, the return types of `:hackney.request/5` are:

```erlang
{ok, integer(), list(), client_ref()}
| {ok, integer(), list()}
| {ok, client_ref()}
| {error, term()}
```

So the branch `{:ok, status, headers, body} when is_binary(body)` doesn't seem to make sense. But then I'm wondering why dialyzer doesn't put out a warning? Is that branch safe to remove?

### CODE REVIEW

**Comment by scrogson** [comment]
> So the branch `{:ok, status, headers, body} when is_binary(body)` doesn't seem to make sense.

I can't remember exactly, but I think this is to support to `with_body: true` option.

**Comment by woylie** [comment]
Indeed. I added a test case for that.

**Comment by woylie** [comment]
I'm done here, by the way, so you can merge this, if you want. Otherwise I'll close it.

**Comment by scrogson** [comment]
> I'm done here, by the way, so you can merge this, if you want. Otherwise I'll close it.

Ok, great. I'll review.

**Comment by scrogson** [comment]
@woylie thank you!

**Pull request merged**
